In [ ]:
# youtube = https://www.youtube.com/watch?v=Jyo53pAyVAM

In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [8]:
X.shape,y.shape

((442, 10), (442,))

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)


In [10]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [15]:
print(reg.coef_)
print(reg.intercept_)

[  -9.16088483 -205.46225988  516.68462383  340.62734108 -895.54360867
  561.21453306  153.88478595  126.73431596  861.12139955   52.41982836]
151.88334520854633


In [16]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399387660024645

### MAKING A REGRESSOR CLASS

In [66]:
class GDregressor:
    
    def __init__(self,learning_rate = 0.01, epoch=100):
        self.lr = learning_rate
        self.epoch = epoch
        self.coef_ = None
        self.intercept_ = None
    
    def fit(self,X_train,y_train):
        # first taking intercept as 0 and coef_ as 1 for all columns.
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        print(self.coef_)
        
        for i in range(self.epoch):
            y_hat = np.dot(X_train,self.coef_) + self.intercept_   
            intercept_der = -2 * np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            
            coef_der =  -2 * (np.dot((y_train - y_hat),X_train)/X_train.shape[0])
            self.coef_  = self.coef_ - (self.lr * coef_der)
            
        print(self.coef_, self.intercept_)
            
    
    def predict(self,X_test):
        return np.dot(X_train,self.coef_) + self.intercept_  

In [67]:
gdr = GDregressor(epoch=270)
gdr.fit(X_train,y_train)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 5.36274016  1.75489268 12.25721209  9.91308116  5.00677773  3.98823419
 -6.08794825  8.44144118 12.37801496  7.87372918] 149.8920424729192


In [68]:
y_pred = gdr.predict(X_test)
y_pred

array([147.56112631, 148.68784069, 147.33667941, 149.64727164,
       145.87400441, 151.52169899, 153.54463995, 150.87290979,
       151.91217919, 148.88251529, 152.49191502, 149.06321076,
       151.50183099, 145.86323859, 149.54755013, 152.02956491,
       152.29717216, 150.42696868, 149.01276038, 150.92246174,
       151.52123594, 152.5223603 , 150.82051029, 152.2744511 ,
       150.61441789, 146.46865032, 148.14216229, 145.58671744,
       150.56119618, 150.48201532, 146.51716426, 152.60576887,
       151.8440636 , 151.1097365 , 152.9962449 , 153.44916132,
       153.21744692, 151.84926651, 146.44491095, 151.22167361,
       145.028294  , 150.26498248, 149.26081296, 147.00725513,
       151.07103379, 146.42097823, 148.873395  , 149.70746283,
       149.13574958, 153.3187954 , 152.63179472, 152.27313893,
       151.92455948, 150.40538198, 147.36455733, 148.48116015,
       149.2953174 , 149.18099318, 150.34730096, 146.92091404,
       152.00080875, 147.05726757, 151.05698141, 147.90

In [70]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [89]:
r2_score(y_test,y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [89, 353]